project:
  type: website
  output-dir: docs

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: table.qmd
        text: Table

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true